version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "2.7"
    nodejs: "18"
    rust: "1.64"
    golang: "1.19"
  apt_packages:
    - cmake

python:
  install:
    - requirements: .py-requirements.txt
